idf_component_register(SRCS "ethernet_main.c"
                            "common/ethernet_init.c"
                            "util/e_time.c"
                            "protocol/mqtt/mqtt.c"
                            "protocol/mqtt/subcriber.c"
                            "protocol/mqtt/publisher.c"
                            "app/led/led.c"
                       INCLUDE_DIRS "."
                       INCLUDE_DIRS "../include"
                       )
